# Generated by Django 2.2 on 2019-05-06 03:40

from django.db import migrations, models
import infs3202.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_validated',
            field=models.BooleanField(default=False, help_text='Is sat to true when user verifies email.'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_key',
            field=models.CharField(default=infs3202.users.models.get_default_email_verification_key, help_text='UUID used to verify the users email.', max_length=36),
        ),
    ]
