language: node_js
node_js: "stable"

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

jobs:
  include:
    - stage: setup
      script: cd ./frontend && yarn install

    - stage: build
      script: cd ./frontend && REACT_APP_API_URL=API_URL yarn build

    - stage : "Deploy staging"
      script:
        deploy:
        - provider: firebase
          skip_cleanup: true
          token:
            secure: $FIREBASE_TOKEN
          project: "staging"
          local_dir: build
          on:
            branch: travis

    - stage : "Deploy production"
      script:
        deploy:
        - provider: firebase
          skip_cleanup: true
          token:
            secure: $FIREBASE_TOKEN
          project: "production"
          local_dir: build
          on:
            branch: master
