# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - ci-cd

    docker:
      - image: circleci/node:11.14

    working_directory: ~/infs3202

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "./frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: 'Install dependencies'
          command: |
            cd frontend
            yarn install
            yarn add firebase-tools

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "./frontend/package.json" }}

      - run:
          name: 'Build project'
          command: cd frontend && API_URL=$API_URL && yarn build

      - run:
          name: 'Deploy to Firebase'
          command: |
            cd frontend
            './frontend/node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
