# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - ci-cd

    docker:
      - image: circleci/node:11.14

    working_directory: ~/infs3202

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: 'Install dependencies'
          command: cd frontend && yarn install

      - save_cache:
          paths:
            - ./frontend/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: 'Build project'
          command: cd frontend && API_URL=$API_URL && yarn build

      - run:
          name: 'Deploy to Firebase'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
